- hosts: controllers
  become: 'yes'
  tasks:
#    - name: Resetting kubeadm
 #     shell: kubeadm reset ! systemctl restart kubelet
    - name: Initialize the cluster
      shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
    - name: Create .kube directory
      become: 'yes'
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory
        mode: 493
    - name: Copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: 'yes'
        owner: kube
#    - name: Fixing kube port problem beforehand
 #     shell: kubectl --kubeconfig=/home/dialog/.kube/config -n kube-system get configmap/kube-proxy -o yaml

    - name: Install Pod Network
      become: 'yes'
      become_user: kube
      shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml | kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml
      args:
        chdir: $HOME
    - name: Token for joining worker nodes
      become: 'yes'
      become_user: kube
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command
    - name: Copy join command to local file
      become: 'yes'
      local_action: >-
        copy content=" {{ kubernetes_join_command.stdout_lines[0] }}"
        dest="/tmp/kubernetes_join_command" mode=0777
